package br.com.nhac.backend_nhac.exceptions;

public enum ErrorCode {
    PRODUTO_NAO_ENCONTRADO("PRODUTO_NAO_ENCONTRADO"),
    LOJA_NAO_ENCONTRADA("LOJA_NAO_ENCONTRADA"),
    LOJA_FECHADA("LOJA_FECHADA"),
    ESTOQUE_INSUFICIENTE("ESTOQUE_INSUFICIENTE"),
    PAGAMENTO_RECUSADO("PAGAMENTO_RECUSADO"),
    CREDENCIAIS_INVALIDAS("CREDENCIAIS_INVALIDAS"),
    ACESSO_NEGADO("ACESSO_NEGADO"),
    VALIDACAO_FALHOU("VALIDACAO_FALHOU"),
    ERRO_INTERNO_SERVIDOR("ERRO_INTERNO_SERVIDOR"),
    RECURSO_NAO_ENCONTRADO("RECURSO_NAO_ENCONTRADO"),
    REGRA_DE_NEGOCIO("REGRA_DE_NEGOCIO"),
    TENTATIVAS_LOGIN_EXCEDIDAS("TENTATIVAS_LOGIN_EXCEDIDAS"),
    CAMPO_OBRIGATORIO_FALTANDO("CAMPO_OBRIGATORIO_FALTANDO"),
    PRODUTO_INATIVO("PRODUTO_INATIVO"),
    QUANTIDADE_INVALIDA("QUANTIDADE_INVALIDA"),
    SERVICO_INDISPONIVEL("SERVICO_INDISPONIVEL"),
    TRANSICAO_STATUS_INVALIDA("TRANSICAO_STATUS_INVALIDA"),
    IDEMPOTENCIA_CONFLITO("IDEMPOTENCIA_CONFLITO"),
    PEDIDO_ATIVO("PEDIDO_ATIVO"),
    CODIGO_ENTREGA_OBRIGATORIO("CODIGO_ENTREGA_OBRIGATORIO"),
    CODIGO_ENTREGA_INVALIDO("CODIGO_ENTREGA_INVALIDO"),
    CODIGO_ENTREGA_BLOQUEADO("CODIGO_ENTREGA_BLOQUEADO"),
    PAGAMENTO_INDISPONIVEL("PAGAMENTO_INDISPONIVEL");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
